name: Unity-Activation

on: [push]

jobs:
  active:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Request manual activation file
      id: getManualLicenseFile
      uses: game-ci/unity-request-activation-file@v2.0-alpha-1
      with:
        unityVersion: 2019.4.8f1
        
    - name: Expose as artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.getManualLicenseFile.outputs.filePath }}
        path: ${{ steps.getManualLicenseFile.outputs.filePath }}
